# Generated by Django 4.2.3 on 2023-07-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infoUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(blank=True, max_length=32, null=True)),
                ('apellidoUsuario', models.CharField(blank=True, max_length=32, null=True)),
                ('nroCelular', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
