# Generated by Django 4.2.3 on 2023-07-22 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_direccionusuario_infousuarios_direccioninfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('fechaInicio', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='direccionusuario',
            name='cursoUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2.cursoinfo'),
        ),
    ]
