# Generated by Django 4.2.3 on 2023-07-22 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_cursoinfo_direccionusuario_cursousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccionusuario',
            name='cursoUsuario',
        ),
        migrations.AddField(
            model_name='infousuarios',
            name='cursoUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2.cursoinfo'),
        ),
    ]
